"""add product_search_counts

Revision ID: 12408b154f23
Revises: 92ad8b9e33fc
Create Date: 2026-09-01 14:40:47.542772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '12408b154f23'
down_revision: Union[str, Sequence[str], None] = '92ad8b9e33fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_search_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_search_counts_product_id'), 'product_search_counts', ['product_id'], unique=True)
    op.alter_column('chat_history', 'topic_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_chat_history_topic'), table_name='chat_history')
    op.drop_constraint(op.f('chat_history_ibfk_1'), 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'chat_topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_history', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('topic', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key(op.f('chat_history_ibfk_1'), 'chat_history', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_chat_history_topic'), 'chat_history', ['topic'], unique=False)
    op.alter_column('chat_history', 'topic_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_product_search_counts_product_id'), table_name='product_search_counts')
    op.drop_table('product_search_counts')
    # ### end Alembic commands ###
