"""created table user_searches

Revision ID: e152518754cd
Revises: b97ff8fa756b
Create Date: 2026-09-05 10:40:52.424234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e152518754cd'
down_revision: Union[str, Sequence[str], None] = 'b97ff8fa756b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('searched_query', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_searches_created_at'), 'user_searches', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_searches_searched_query'), 'user_searches', ['searched_query'], unique=False)
    op.create_index(op.f('ix_user_searches_user_id'), 'user_searches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_searches_user_id'), table_name='user_searches')
    op.drop_index(op.f('ix_user_searches_searched_query'), table_name='user_searches')
    op.drop_index(op.f('ix_user_searches_created_at'), table_name='user_searches')
    op.drop_table('user_searches')
    # ### end Alembic commands ###
